services:
  EschoolMonolith.db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: EschoolMonolith
      POSTGRES_PASSWORD: 1234
    ports:
      - 5100:5432
    volumes:
      - eschooldb:/var/lib/postgresql/data
volumes:
  eschooldb:
